# Generated by Django 3.0.2 on 2020-01-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_pic.png', upload_to='profile_pics'),
        ),
    ]
