# Generated by Django 3.0.2 on 2020-01-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=200)),
                ('PubTime', models.DateTimeField()),
                ('OriPrice', models.FloatField(default=0)),
                ('DisPrice', models.FloatField(default=0)),
                ('link', models.URLField(max_length=500)),
                ('Tag', models.CharField(max_length=200)),
                ('click', models.IntegerField(default=0)),
                ('EndTime', models.DateTimeField()),
            ],
        ),
    ]
