# Generated by Django 3.0.2 on 2020-01-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discountsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='link',
            new_name='Shoplink',
        ),
        migrations.AddField(
            model_name='product',
            name='imglink',
            field=models.URLField(default=123123, max_length=500),
            preserve_default=False,
        ),
    ]
